name: 'Fetch Github Release Asset'
description: 'Downloads an asset from a Github release'

inputs:
  repo:
    description: 'org/repo to download from'
    required: false
    default: ''
  version:
    description: 'version of the release to download from'
    required: false
    default: 'latest'
  file:
    description: 'name of the file in the release to download'
    required: true
  output_file:
    description: 'optional name of the file to write out'
    required: false
    default: ''
  token:
    description: 'optional Personal Access Token to access external repository'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.version }}
    - ${{ inputs.file }}
    - ${{ inputs.output_file }}
    - ${{ inputs.token }}

outputs:
  version:
    description: 'The version of the release or tag'

branding:
  icon: 'download-cloud'
  color: 'orange'
